### ISSUE TITLE
release v9.0.0

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1118]
I'll release in the morning.  Diff of changes in this release:
https://github.com/TypeStrong/ts-node/compare/v8.10.2...master

The tag for 8.10.2 ([here](https://github.com/TypeStrong/ts-node/commit/44c61af923baaa9f3aa4b84a93fe903cf44f10fb)) is not in master's history.  I can't remember exactly why; I think I made a mistake with 8.10.2 or I thought it would be the start of an 8.x branch of non-breaking changes, distinct from master.  The parent commit, v8.10.2~1 *is* on master, so the diff above is effectively starting there.

## Tasks
- [x] publish to npm
- [x] add release notes to GH Release
- [x] send updated schema to schemastore
- [x] reply on affected tickets that 9.0 is out, if it looks like someone commented recently

# v9.0.0

*Breaking changes are labelled [BREAKING] below.

**Added**

- Throw `ERR_REQUIRE_ESM` when a file is `require()`d which should be loaded as ESM (#1031)
- Re-add `"exports"` declaration to package.json in backwards-compatible way, enabling `node --loader ts-node/esm` without file extension (#1028)
- Allow specifying `"require"` option via tsconfig (#925)
- REPL respects node's `NODE_NO_READLINE` environment variable (#1090)
- Add a transpile-only entrypoint for ESM loader: `node --loader ts-node/esm/transpile-only` (#1102) @concision

**Changed**

- [BREAKING] Drops support for node versions < 10 (#1036)

**Fixed**

- [BREAKING] Re-add `realpath`, which should fix workflows that use symlinks, such as `pnpm`, Lerna workspaces, or other mono-repo configurations (#970)
- Compile files within `node_modules` when `--skip-ignore` or `--ignore` options are configured to allow it (#970)
- Fix #884 by not adding all referenced files to `getSourceFileNames`/`rootNames` (#999)
- Fix #996: bump `projectVersion` every time `getSourceFileNames` changes, avoiding accidentally outdated typechecking (#998)
- Fix #1051: pass transformers object to `ts.transpileModule` (#1054) @thetutlage
- Fix #1060: use source maps for stack traces in ESM modules (#1087)
- Fix #1072: Respect `--experimental-specifier-resolution` coming from `NODE_OPTIONS` in ESM loader (#1085) @evg656e
- Fix #1098: ESM loader should skip `.cjs`, `.mjs`, and any unexpected file extensions (#1103) @concision

**Docs**

- Better explain how to compile imports, either CommonJS or using experimental ESM loader. Resolves #1075 (#1086)

**Misc**

- Fix, re-enable, and add various tests (#1044, #1088, #1108, #1110, #1109, #1115, #1043, #999)

https://github.com/TypeStrong/ts-node/compare/v8.10.2...v9.0.0

---

*will not include these in the changelog*

**Project Infrastructure**

Update .gitignore (#1045) https://github.com/TypeStrong/ts-node/issues/1045
Fix coverage reporting when tests fail; also push to codecov (#1047) https://github.com/TypeStrong/ts-node/issues/1047
ignore vscode config files (#1084) https://github.com/TypeStrong/ts-node/issues/1084
Add helpful links to "Create issue" page, directing people to Discord, StackOverflow, etc (#1097) https://github.com/TypeStrong/ts-node/issues/1097
Add mocharc file (#1105) https://github.com/TypeStrong/ts-node/issues/1105
Add script for adding missing compilerOptions to tsconfig schema (#1107) https://github.com/TypeStrong/ts-node/issues/1107
Fix coverage and testing badges (#1095) https://github.com/TypeStrong/ts-node/issues/1095
[OMIT?] move getOutputTranspileOnly back where it used to be (#1056) https://github.com/TypeStrong/ts-node/issues/1056
Bump lodash from 4.17.15 to 4.17.19 (#1077) https://github.com/TypeStrong/ts-node/issues/1077
bump to typescript 4.0.2 (#1117) https://github.com/TypeStrong/ts-node/issues/1117
