### ISSUE TITLE
Re-export node-relevant @tsconfig/bases; use by default in absence of a tsconfig file

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1202]
This is technically 2 features in one:

a) re-export `@tsconfig/bases` so that a user's tsconfig can, for example, `"extends": "ts-node/node14/tsconfig.json"`
b) in the absence of a tsconfig, check node version and use a suitable default.

https://github.com/tsconfig/bases

This allows ts-node to handle bare scripts using modern language features.  For example, bigint literals require a modern "target" option which tsc does *not* adopt by default.  If someone tried to write a ts-node shebang script using bigint literals, it would fail to compile unless they accompanied it with a tsconfig.json.

## TODO

* [x] add CLI flag --skip-default-project
* [x] update programmatic option to match?  `skipDefaultProject`?
* [x] what to name the CLI flag
  * https://discord.com/channels/508357248330760243/508357707602853888/814950988069732352
  * `--no-implicit-project`
  * `--no-implicit-compiler-options`
* [x] extract CLI flag to another PR; do not implement it in this first pass
* [x] add tests
* [x] newer @tsconfig/bases are incompatible with Typescript 2.7: how to handle this?
  * can check `ts.ScriptTarget` and `ts.libs` to ensure they have the necessary entries.  If node14 config is incompatible, try node12, then node10
  * TS 3.4 added target ES2019 but does not have the necessary `require('typescript').libs` entries for the node12 tsconfig, so checking libs is necessary

**Comment by cspotcode** [comment]
Will need to add an option `--skip-default-project`

If you *really* want `ts-node` to use default tsc compiler options:
`ts-node --skip-project --skip-default-project ./index.ts`

This is verbose; the rationale is that people will *rarely* want to do this.

The default, `ts-node ./index.ts` or `ts-node`, will load @tsconfig/node* where it picks node10, node12, or node14 based on node runtime's major version number.

**Comment by cspotcode** [comment]
When implementing, should be sure to avoid triggering any logic that cares about the path of the tsconfig file.  In other words, we don't want to affect scope, or ignore, or anything like that.  We just want to get the tsconfig compilerOptions such as "target" and "lib".
