### ISSUE TITLE
v10.0.0 milestone

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1293]
Gonna try using a "milestone" to track this release.

https://github.com/TypeStrong/ts-node/milestone/1

Mostly just documentation in the new website, and a few more logging statements to aid with debugging new features such as implicit configs.

These are good tickets for newcomers to help with.  Feel free to ask for clarification in any of the tickets; some are vague and do not have a clear to-do list.

* [x] Finish all milestone tickets
* [x] prepare changelog
- [x] push apiextractor report to github
- [x] Merge `docs` into `main`
- [x] remove WIP banner from website config
- [x] `npm install && npm prune` to cleanup the `package-lock.json`; commit and push it
- [x] Rebuild the README (see instructions above, necessary because npmjs.com renders the readme)
- [x] push README to github
- [x] Make sure both logo and screenshot render correctly on both website and README.md
* [x] [publish release](https://github.com/TypeStrong/ts-node/blob/main/CONTRIBUTING.md#release-checklist)
  * [x] publish to npm
  * [x] Post changelog to GH release
  * [x] create discussion topic; add # to changelog
  * [x] add milestone link to bottom of changelog https://github.com/TypeStrong/ts-node/milestone/1
  * [x] move `docs` to head of `main`
  * [x] confirm the website has rebuilt
  * [x] Send Schemastore PR: SchemaStore/schemastore#1620
* [x] Ensure READMEs for v9 on npmjs.com continues to render images correctly (image URLs are pointed at github main branch)
* [x] Prepare next milestone
