### ISSUE TITLE
[EPIC] Diagnostics, warnings

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1504]
An epic to track diagnostic logging, warnings, and tools users can use to better understand what's happening.

The goal is for users to diagnose their own problems and walk away from the experience with a better understanding of ts-node rather than frustration.

* Known problematic tsconfigs 
  * [ ] #1248
  * [ ] #1069 
  * [ ] #1691
  * [ ] Warn to enable resolver when using node12/node16/nodenext
  * [ ] Warn when nodenext/node16 is used with an incompatible moduleResolution mode (https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1073153636)
* [ ] #1445 
* [ ] #1461 
* [ ] #1366 
* [ ] #1446 
* [ ] #1407 
* [ ] #1271 
* [ ] #1203 
* [ ] #960 
* [ ] When transpiled code attempts to require tslib, regenerator-runtime, or @swc/helpers, log a helpful warning about adding those dependencies; link to relevant docs page
* [x] #1692
* [x] #1389 
* [x] #1128 
* [x] #1323
